name: grocery_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^4.2.0
  iconsax: ^0.0.8
  provider: ^6.1.5+1
  cloud_firestore: ^6.0.3
  google_sign_in: ^7.2.0
  firebase_auth: ^6.1.1
  image_picker: ^1.2.0
  firebase_storage: ^13.0.3
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/google.png
    - assets/logo.png
    - assets/profile.png
    - assets/icons/logoIcon.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"
